server:
  port: 10004

spring:
  application:
    name: spring-ai-alibaba-zhipuai-chat-client-example

  ai:
    zhipuai:
      base-url: "open.bigmodel.cn/api/paas"
      api-key: "5489de76839d4c33973125ab4b0cfc17.PGnP7DviLB8xM64x"
